// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: idallocator.proto
#ifndef GRPC_idallocator_2eproto__INCLUDED
#define GRPC_idallocator_2eproto__INCLUDED

#include "idallocator.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace idallocator {

class IdAllocatorService final {
 public:
  static constexpr char const* service_full_name() {
    return "idallocator.IdAllocatorService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status AllocateId(::grpc::ClientContext* context, const ::idallocator::AllocateIdReq& request, ::idallocator::AllocateIdResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::idallocator::AllocateIdResp>> AsyncAllocateId(::grpc::ClientContext* context, const ::idallocator::AllocateIdReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::idallocator::AllocateIdResp>>(AsyncAllocateIdRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::idallocator::AllocateIdResp>> PrepareAsyncAllocateId(::grpc::ClientContext* context, const ::idallocator::AllocateIdReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::idallocator::AllocateIdResp>>(PrepareAsyncAllocateIdRaw(context, request, cq));
    }
    virtual ::grpc::Status BatchAllocateId(::grpc::ClientContext* context, const ::idallocator::BatchAllocateIdReq& request, ::idallocator::BatchAllocateIdResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::idallocator::BatchAllocateIdResp>> AsyncBatchAllocateId(::grpc::ClientContext* context, const ::idallocator::BatchAllocateIdReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::idallocator::BatchAllocateIdResp>>(AsyncBatchAllocateIdRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::idallocator::BatchAllocateIdResp>> PrepareAsyncBatchAllocateId(::grpc::ClientContext* context, const ::idallocator::BatchAllocateIdReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::idallocator::BatchAllocateIdResp>>(PrepareAsyncBatchAllocateIdRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void AllocateId(::grpc::ClientContext* context, const ::idallocator::AllocateIdReq* request, ::idallocator::AllocateIdResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AllocateId(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::idallocator::AllocateIdResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void BatchAllocateId(::grpc::ClientContext* context, const ::idallocator::BatchAllocateIdReq* request, ::idallocator::BatchAllocateIdResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void BatchAllocateId(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::idallocator::BatchAllocateIdResp* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::idallocator::AllocateIdResp>* AsyncAllocateIdRaw(::grpc::ClientContext* context, const ::idallocator::AllocateIdReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::idallocator::AllocateIdResp>* PrepareAsyncAllocateIdRaw(::grpc::ClientContext* context, const ::idallocator::AllocateIdReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::idallocator::BatchAllocateIdResp>* AsyncBatchAllocateIdRaw(::grpc::ClientContext* context, const ::idallocator::BatchAllocateIdReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::idallocator::BatchAllocateIdResp>* PrepareAsyncBatchAllocateIdRaw(::grpc::ClientContext* context, const ::idallocator::BatchAllocateIdReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status AllocateId(::grpc::ClientContext* context, const ::idallocator::AllocateIdReq& request, ::idallocator::AllocateIdResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::idallocator::AllocateIdResp>> AsyncAllocateId(::grpc::ClientContext* context, const ::idallocator::AllocateIdReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::idallocator::AllocateIdResp>>(AsyncAllocateIdRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::idallocator::AllocateIdResp>> PrepareAsyncAllocateId(::grpc::ClientContext* context, const ::idallocator::AllocateIdReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::idallocator::AllocateIdResp>>(PrepareAsyncAllocateIdRaw(context, request, cq));
    }
    ::grpc::Status BatchAllocateId(::grpc::ClientContext* context, const ::idallocator::BatchAllocateIdReq& request, ::idallocator::BatchAllocateIdResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::idallocator::BatchAllocateIdResp>> AsyncBatchAllocateId(::grpc::ClientContext* context, const ::idallocator::BatchAllocateIdReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::idallocator::BatchAllocateIdResp>>(AsyncBatchAllocateIdRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::idallocator::BatchAllocateIdResp>> PrepareAsyncBatchAllocateId(::grpc::ClientContext* context, const ::idallocator::BatchAllocateIdReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::idallocator::BatchAllocateIdResp>>(PrepareAsyncBatchAllocateIdRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void AllocateId(::grpc::ClientContext* context, const ::idallocator::AllocateIdReq* request, ::idallocator::AllocateIdResp* response, std::function<void(::grpc::Status)>) override;
      void AllocateId(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::idallocator::AllocateIdResp* response, std::function<void(::grpc::Status)>) override;
      void BatchAllocateId(::grpc::ClientContext* context, const ::idallocator::BatchAllocateIdReq* request, ::idallocator::BatchAllocateIdResp* response, std::function<void(::grpc::Status)>) override;
      void BatchAllocateId(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::idallocator::BatchAllocateIdResp* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::idallocator::AllocateIdResp>* AsyncAllocateIdRaw(::grpc::ClientContext* context, const ::idallocator::AllocateIdReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::idallocator::AllocateIdResp>* PrepareAsyncAllocateIdRaw(::grpc::ClientContext* context, const ::idallocator::AllocateIdReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::idallocator::BatchAllocateIdResp>* AsyncBatchAllocateIdRaw(::grpc::ClientContext* context, const ::idallocator::BatchAllocateIdReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::idallocator::BatchAllocateIdResp>* PrepareAsyncBatchAllocateIdRaw(::grpc::ClientContext* context, const ::idallocator::BatchAllocateIdReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AllocateId_;
    const ::grpc::internal::RpcMethod rpcmethod_BatchAllocateId_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status AllocateId(::grpc::ServerContext* context, const ::idallocator::AllocateIdReq* request, ::idallocator::AllocateIdResp* response);
    virtual ::grpc::Status BatchAllocateId(::grpc::ServerContext* context, const ::idallocator::BatchAllocateIdReq* request, ::idallocator::BatchAllocateIdResp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AllocateId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_AllocateId() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AllocateId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AllocateId(::grpc::ServerContext* context, const ::idallocator::AllocateIdReq* request, ::idallocator::AllocateIdResp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAllocateId(::grpc::ServerContext* context, ::idallocator::AllocateIdReq* request, ::grpc::ServerAsyncResponseWriter< ::idallocator::AllocateIdResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_BatchAllocateId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_BatchAllocateId() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_BatchAllocateId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchAllocateId(::grpc::ServerContext* context, const ::idallocator::BatchAllocateIdReq* request, ::idallocator::BatchAllocateIdResp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBatchAllocateId(::grpc::ServerContext* context, ::idallocator::BatchAllocateIdReq* request, ::grpc::ServerAsyncResponseWriter< ::idallocator::BatchAllocateIdResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AllocateId<WithAsyncMethod_BatchAllocateId<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_AllocateId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_AllocateId() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::idallocator::AllocateIdReq, ::idallocator::AllocateIdResp>(
          [this](::grpc::ServerContext* context,
                 const ::idallocator::AllocateIdReq* request,
                 ::idallocator::AllocateIdResp* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->AllocateId(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_AllocateId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AllocateId(::grpc::ServerContext* context, const ::idallocator::AllocateIdReq* request, ::idallocator::AllocateIdResp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void AllocateId(::grpc::ServerContext* context, const ::idallocator::AllocateIdReq* request, ::idallocator::AllocateIdResp* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_BatchAllocateId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_BatchAllocateId() {
      ::grpc::Service::experimental().MarkMethodCallback(1,
        new ::grpc::internal::CallbackUnaryHandler< ::idallocator::BatchAllocateIdReq, ::idallocator::BatchAllocateIdResp>(
          [this](::grpc::ServerContext* context,
                 const ::idallocator::BatchAllocateIdReq* request,
                 ::idallocator::BatchAllocateIdResp* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->BatchAllocateId(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_BatchAllocateId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchAllocateId(::grpc::ServerContext* context, const ::idallocator::BatchAllocateIdReq* request, ::idallocator::BatchAllocateIdResp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void BatchAllocateId(::grpc::ServerContext* context, const ::idallocator::BatchAllocateIdReq* request, ::idallocator::BatchAllocateIdResp* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_AllocateId<ExperimentalWithCallbackMethod_BatchAllocateId<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AllocateId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_AllocateId() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AllocateId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AllocateId(::grpc::ServerContext* context, const ::idallocator::AllocateIdReq* request, ::idallocator::AllocateIdResp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_BatchAllocateId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_BatchAllocateId() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_BatchAllocateId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchAllocateId(::grpc::ServerContext* context, const ::idallocator::BatchAllocateIdReq* request, ::idallocator::BatchAllocateIdResp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AllocateId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_AllocateId() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AllocateId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AllocateId(::grpc::ServerContext* context, const ::idallocator::AllocateIdReq* request, ::idallocator::AllocateIdResp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAllocateId(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_BatchAllocateId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_BatchAllocateId() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_BatchAllocateId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchAllocateId(::grpc::ServerContext* context, const ::idallocator::BatchAllocateIdReq* request, ::idallocator::BatchAllocateIdResp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBatchAllocateId(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_AllocateId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_AllocateId() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->AllocateId(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_AllocateId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AllocateId(::grpc::ServerContext* context, const ::idallocator::AllocateIdReq* request, ::idallocator::AllocateIdResp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void AllocateId(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_BatchAllocateId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_BatchAllocateId() {
      ::grpc::Service::experimental().MarkMethodRawCallback(1,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->BatchAllocateId(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_BatchAllocateId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchAllocateId(::grpc::ServerContext* context, const ::idallocator::BatchAllocateIdReq* request, ::idallocator::BatchAllocateIdResp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void BatchAllocateId(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AllocateId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_AllocateId() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::idallocator::AllocateIdReq, ::idallocator::AllocateIdResp>(std::bind(&WithStreamedUnaryMethod_AllocateId<BaseClass>::StreamedAllocateId, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_AllocateId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AllocateId(::grpc::ServerContext* context, const ::idallocator::AllocateIdReq* request, ::idallocator::AllocateIdResp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAllocateId(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::idallocator::AllocateIdReq,::idallocator::AllocateIdResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_BatchAllocateId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_BatchAllocateId() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::idallocator::BatchAllocateIdReq, ::idallocator::BatchAllocateIdResp>(std::bind(&WithStreamedUnaryMethod_BatchAllocateId<BaseClass>::StreamedBatchAllocateId, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_BatchAllocateId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status BatchAllocateId(::grpc::ServerContext* context, const ::idallocator::BatchAllocateIdReq* request, ::idallocator::BatchAllocateIdResp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedBatchAllocateId(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::idallocator::BatchAllocateIdReq,::idallocator::BatchAllocateIdResp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AllocateId<WithStreamedUnaryMethod_BatchAllocateId<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AllocateId<WithStreamedUnaryMethod_BatchAllocateId<Service > > StreamedService;
};

}  // namespace idallocator


#endif  // GRPC_idallocator_2eproto__INCLUDED
